#:schema https://fnox.jdx.dev/schema.json

if_missing = "error"

[providers]
keychain = { type = "keychain", service = "static-env-var" }
pass = { type = "password-store", prefix = "static-env-var/" }
